spring:
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

jpa:
  hibernate:
    ddl-auto: none  # Desativar a criação automática de tabelas pelo Hibernate
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

flyway:
  enabled: true
  baseline-on-migrate: true